# Generated by Django 2.1.7 on 2019-08-27 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('PE', 'Pernambuco'), ('PB', 'Paraíba'), ('CE', 'Ceará'), ('SP', 'São Paulo'), ('SE', 'SERGIPE'), ('RJ', 'Rio de Janeiro'), ('RS', 'Rio Grande do Sul'), ('RN', 'Rio Grande do Norte'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PR', 'Paraná'), ('PI', 'Piaui'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('TO', 'Tocantins')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=None, null=True)),
                ('longitude', models.FloatField(default=None, null=True)),
                ('description', models.CharField(default=None, max_length=500, null=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makoni.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=10)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makoni.Endereco')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=500, null=True)),
                ('reference_point', models.CharField(default=None, max_length=300, null=True)),
                ('url_photo', models.CharField(default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router', models.CharField(default=None, max_length=30)),
                ('localization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makoni.Localization')),
                ('user_point_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makoni.Person')),
            ],
        ),
        migrations.AddField(
            model_name='localization',
            name='photos',
            field=models.ManyToManyField(to='makoni.Photo', verbose_name='list of photos'),
        ),
    ]
