# Generated by Django 2.1.7 on 2019-08-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makoni', '0002_auto_20190827_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=300, null=True)),
                ('original', models.ImageField(blank=True, null=True, upload_to='images/locations')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='images_origin',
            field=models.ManyToManyField(to='makoni.Image', verbose_name='galery of images'),
        ),
    ]
